name: Build and Deploy

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Use yarn
        run: |
          yarn
          yarn build

      - name: Deploy
        run: |
          cd build
          echo "
            ${{ secrets.PASSWORD }}
            $(find . -type d | sed -e 's/^/mkdir /;')
            put -r .
            exit
          " > /tmp/commands
          ${{ secrets.PROCESS }} < /tmp/commands
